services:
  postgres:
    image: postgres:15-alpine
    container_name: golang_template_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=identity
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
